env: "local"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "postgres"
  sslmode: "disable"

http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s